# Stage 1: Install dependencies
FROM node:18-alpine AS dependencies
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

# Stage 2: Build the application
FROM node:18 AS builder
WORKDIR /app
COPY . . 
COPY --from=dependencies /app/node_modules ./node_modules
RUN yarn build

# Stage 3: Serve the application
FROM node:18 AS runner
WORKDIR /app

# Copy only the necessary files for production
COPY --from=dependencies /app/node_modules ./node_modules
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/package.json ./package.json

# Disable telemetry
ENV NEXT_TELEMETRY_DISABLED 1

# Expose the application on port 3000
EXPOSE 3000
CMD ["yarn", "start"]
